sudo: required
dist: xenial
group: edge
language: node_js
node_js:
  - 8.10.0
services:
  - postgresql
addons:
  postgresql: "9.4"
  chrome: stable
env:
  global:
  - PGPORT=5432
  - AWS_ACCESS_KEY_ID=dummy
  - AWS_SECRET_KEY=dummy
  - S3_BUCKET_NAME=dummy
before_install:
  - rvm install 2.5.1
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem install bundler -v '2.0.2'
install:
  - bundle install
  - yarn install
  - bundle exec rake db:create db:migrate
before_script:
  - bundle exec rails runner "Webdrivers::Chromedriver.update"
script:
  - bundle exec rspec
