#!/bin/bash

set -e

[ -e latest.dump ] && rm latest.dump

heroku pg:backups:capture --app "$1"

heroku pg:backups:download --app "$1"

bundle exec rake db:drop db:create

pg_restore --verbose --clean --no-acl --no-owner -h localhost -d mox_development latest.dump
