#!/bin/bash

set -e

git checkout master

git pull

bundle check || bundle install

bundle exec rake db:migrate

bundle exec rspec

yarn install

# TODO: add some frontend tests
# npm run test

git push production master:master
