#!/bin/bash

set -e

git checkout staging

git pull

bundle check || bundle install
bundle exec rake db:migrate
bundle exec rspec

# TODO: add some frontend tests
# yarn install
# npm run test

git push staging staging:master
heroku run rake db:migrate --app mox-staging
